### Numpy

#### Some operations on Zeros ans Ones array

In [1]:
import numpy as np

In [2]:
###crete array zeros
arr1=np.zeros((5,5),dtype=int)

In [3]:
#### make the diagonal elements 1
np.fill_diagonal(arr1, 5)
arr1

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [4]:
a = np.zeros((3, 3), int)
np.fill_diagonal(a, 1)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
###Flip anti-diagonal
a = np.zeros((3, 3), int);
np.fill_diagonal(np.fliplr(a), 1)
a

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [6]:
###Flip anti-diagonal
a = np.zeros((3, 3), int);
np.fill_diagonal(np.fliplr(a), [1,2,3]) ##horizontal flip
a

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [7]:
np.fill_diagonal(np.flipud(a), [1,2,3])  # Vertical flip
a

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

In [8]:
###center elements =1 and outer edge=0
arr1=np.zeros((4,4),dtype=int)
arr1[1:-1, 1:-1] = 1
arr1

array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [9]:
###center elements =0 and outer edge=1
arr1=np.ones((5,5),dtype=int)
arr1[1:-1, 1:-1] = 0
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [10]:
####print z in the matrix
out = np.zeros((5, 5), int);
np.fill_diagonal(np.fliplr(out),1)
out[[0,-1]] = 1
out

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1]])